site_name: CROCOA

theme: 
  name: material
  palette:
    scheme: slate

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
  
nav:
  - Home: index.md
  - Examples: examples.md
  - Manual shifts: manual_shifts.md
  - Potential problems: potential_problems.md
  - API Docs: apidocs.md
